### ISSUE TITLE
TypeError: cli.init is not a function

### ISSUE THREAD

**Issue by brsnik** [demchenkoalex/react-native-better-template#3]
Been getting this error when trying to initialize a new project using your template.

```/opt/homebrew/lib/node_modules/react-native-cli/index.js:302
  cli.init(root, projectName);
      ^

TypeError: cli.init is not a function
    at run (/opt/homebrew/lib/node_modules/react-native-cli/index.js:302:7)
    at createProject (/opt/homebrew/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/opt/homebrew/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47```

**Comment by demchenkoalex** [comment]
Hey, I did not update this for quite a while, need to deprecate this. TypeScript is now default in React Native and I read that Kotlin will be as well, and Swift is kinda has no point for AppDelegate anymore, since it contains C++ code from new architecture now.

**Comment by brsnik** [comment]
Thanks for the info.
